import type { Scenario } from "./scenarios";

/**
 * 일상 트랙 확장분.
 * 고른 기준은 하나다 — 단어는 다 아는데 입이 안 떨어지는 자리.
 * 새 표현을 가르치는 게 아니라, 이미 아는 걸 빨리 꺼내는 훈련이다.
 */
export const DAILY_EXTRA: Scenario[] = [
  {
    id: "catch-up",
    track: "daily",
    title: "Long time no see",
    titleKo: "오랜만이야, 요즘 어떻게 지내?",
    contextKo: "1년 만에 마주친 지인이 근황을 묻습니다.",
    goalKo: "\"바빴어\"로 끝내지 말고, 바뀐 것 하나를 골라 구체적으로 말한 뒤 상대에게 되묻기.",
    modelDialogue: [
      { speaker: "ai", text: "Hey! It's been ages. How have you been?", ko: "야! 진짜 오랜만이다. 어떻게 지냈어?" },
      {
        speaker: "you",
        text: "Pretty good! A lot's changed, actually — I moved to a new team back in spring.",
        ko: "잘 지냈어! 사실 바뀐 게 좀 많아. 봄에 팀을 옮겼거든.",
      },
      { speaker: "ai", text: "Oh wow, how's that going?", ko: "오, 그건 어때?" },
      {
        speaker: "you",
        text: "Better than I expected. It took a while to settle in, but I'm glad I did it.",
        ko: "생각보다 괜찮아. 적응에 좀 걸리긴 했는데, 하길 잘했어.",
      },
      { speaker: "ai", text: "That's great to hear.", ko: "잘됐네." },
      { speaker: "you", text: "What about you? Still at the same place?", ko: "너는? 아직 거기 다녀?" },
    ],
    chunks: [
      { en: "It's been ages", ko: "진짜 오랜만이야", example: "Hey! It's been ages — how have you been?", exampleKo: "야! 진짜 오랜만이다. 어떻게 지냈어?", note: "Long time no see보다 원어민이 훨씬 자주 씁니다." },
      { en: "A lot's changed, actually", ko: "사실 바뀐 게 좀 많아", example: "A lot's changed, actually — I moved to a new team in spring.", exampleKo: "사실 바뀐 게 좀 많아. 봄에 팀을 옮겼거든.", note: "근황을 '요약'하지 말고 이 한마디로 문을 연 뒤 하나만 고르세요." },
      { en: "It took a while to ~", ko: "~하는 데 좀 걸렸어", example: "It took a while to settle in, but I like it now.", exampleKo: "적응하는 데 좀 걸렸는데, 지금은 좋아.", note: "과정을 말할 때. 결과만 말하면 대화가 거기서 끊깁니다." },
      { en: "I'm glad I did it", ko: "하길 잘했어", example: "It was a big move, but I'm glad I did it.", exampleKo: "큰 결정이었는데, 하길 잘했어.", note: "평가를 한 줄로 닫는 표현. 감정이 들어가야 상대가 받아칩니다." },
      { en: "What about you?", ko: "너는 어때?", example: "What about you? Still at the same place?", exampleKo: "너는? 아직 거기 다녀?", note: "한국 학습자가 가장 자주 빠뜨리는 되묻기. 이게 없으면 대화가 면접이 됩니다." },
    ],
    aiRole: "오랜만에 만난 지인 Emma",
    yourRole: "근황을 전하는 나",
    opening: "Wait — is that you? It's been ages! How have you been?",
    direction:
      "You are Emma, an old acquaintance running into the user by chance. Be warm and curious. Ask follow-up questions about whatever they mention. If they give a one-word answer, ask a gentle follow-up rather than moving on. Share a small update about yourself if they ask. Never correct their English.",
    round1Seconds: 180,
  },
  {
    id: "make-plans",
    track: "daily",
    title: "Let's find a time",
    titleKo: "약속 잡기",
    contextKo: "친구가 만나자고 합니다. 날짜를 정해야 합니다.",
    goalKo: "\"아무 때나 괜찮아\" 금지. 안 되는 날을 말하고, 구체적인 날짜를 먼저 제안하기.",
    modelDialogue: [
      { speaker: "ai", text: "We should grab dinner sometime. Are you free next week?", ko: "언제 저녁 먹자. 다음 주 시간 돼?" },
      {
        speaker: "you",
        text: "I'd love to. Tuesday and Wednesday are tight, but Thursday works for me.",
        ko: "좋지. 화요일 수요일은 빡빡한데, 목요일은 괜찮아.",
      },
      { speaker: "ai", text: "Thursday it is. What time suits you?", ko: "목요일로 하자. 몇 시가 좋아?" },
      {
        speaker: "you",
        text: "Anytime after seven. I can't get out of the office before six thirty.",
        ko: "7시 이후면 언제든. 6시 반 전엔 사무실에서 못 나와.",
      },
      { speaker: "ai", text: "Seven thirty then. I'll book somewhere near you.", ko: "그럼 7시 반. 너희 동네 근처로 예약할게." },
      { speaker: "you", text: "Perfect. Let me know once it's booked.", ko: "좋아. 예약되면 알려줘." },
    ],
    chunks: [
      { en: "I'd love to", ko: "좋지, 그러고 싶어", example: "I'd love to — dinner sounds great.", exampleKo: "좋지. 저녁 완전 좋아.", note: "수락을 감정으로 먼저 표현합니다. Yes 한 마디는 차갑게 들립니다." },
      { en: "~ is tight, but ~ works for me", ko: "~는 빡빡한데 ~는 괜찮아", example: "Wednesday is tight, but Thursday works for me.", exampleKo: "수요일은 빡빡한데, 목요일은 괜찮아.", note: "안 되는 날과 되는 날을 한 문장에. 이게 약속 잡기의 핵심 구조입니다." },
      { en: "What time suits you?", ko: "몇 시가 좋아?", example: "Thursday it is. What time suits you?", exampleKo: "목요일로 하자. 몇 시가 좋아?", note: "What time is good for you보다 자연스럽습니다." },
      { en: "Anytime after ~", ko: "~시 이후면 언제든", example: "Anytime after seven works for me.", exampleKo: "7시 이후면 언제든 괜찮아.", note: "범위로 답하면 상대가 고르기 쉬워집니다." },
      { en: "Let me know once it's ~", ko: "~되면 알려줘", example: "Let me know once it's booked.", exampleKo: "예약되면 알려줘.", note: "대화를 다음 행동으로 넘기며 닫는 표현." },
    ],
    aiRole: "친구 Jake",
    yourRole: "일정을 맞춰야 하는 나",
    opening: "Hey, we keep saying we'll catch up. Let's actually do it — are you free sometime next week?",
    direction:
      "You are Jake, a friendly friend trying to pin down a dinner date. Push gently for specifics: if the user says 'anytime' or 'I'm flexible', say you are bad at picking and ask them to name a day. Agree once they give a concrete day and time. Never correct their English.",
    round1Seconds: 150,
  },
  {
    id: "decline-nicely",
    track: "daily",
    title: "Saying no without the guilt",
    titleKo: "초대 거절하기",
    contextKo: "가고 싶지 않은 모임에 초대받았습니다. 관계는 지켜야 합니다.",
    goalKo: "미안하다는 말만 반복하지 말고: 고마움 → 못 가는 이유 한 줄 → 다음 제안.",
    modelDialogue: [
      { speaker: "ai", text: "We're doing a barbecue on Saturday. You should come!", ko: "토요일에 바비큐 해. 너도 와!" },
      {
        speaker: "you",
        text: "That sounds fun, thanks for thinking of me. Saturday's tough for me though.",
        ko: "재밌겠다, 불러줘서 고마워. 근데 토요일은 좀 어려워.",
      },
      { speaker: "ai", text: "Ah, no worries. Everything okay?", ko: "아, 괜찮아. 무슨 일 있어?" },
      {
        speaker: "you",
        text: "Yeah, I've just got family over that weekend. I'd hate to miss the next one though.",
        ko: "응, 그 주말엔 가족이 와 있어서. 다음엔 꼭 가고 싶어.",
      },
      { speaker: "ai", text: "Definitely, I'll let you know.", ko: "당연하지, 알려줄게." },
      { speaker: "you", text: "Please do. Have fun on Saturday.", ko: "꼭 알려줘. 토요일 재밌게 보내." },
    ],
    chunks: [
      { en: "Thanks for thinking of me", ko: "불러줘서 고마워", example: "That sounds fun — thanks for thinking of me.", exampleKo: "재밌겠다. 불러줘서 고마워.", note: "거절 앞에 반드시 오는 쿠션. 이거 없이 거절하면 관계가 식습니다." },
      { en: "~ is tough for me", ko: "~는 좀 어려워", example: "Saturday's tough for me, unfortunately.", exampleKo: "아쉽게도 토요일은 좀 어려워.", note: "I can't보다 부드럽고, 변명처럼 들리지 않습니다." },
      { en: "I've just got ~ that weekend", ko: "그 주말엔 ~가 있어서", example: "I've just got family over that weekend.", exampleKo: "그 주말엔 가족이 와 있어서.", note: "이유는 딱 한 줄. 길어질수록 변명처럼 들립니다." },
      { en: "I'd hate to miss the next one", ko: "다음엔 꼭 가고 싶어", example: "I'd hate to miss the next one, though.", exampleKo: "그래도 다음엔 꼭 가고 싶어.", note: "거절을 '이번만'으로 만드는 결정적 한 마디." },
      { en: "Have fun on ~", ko: "~ 재밌게 보내", example: "Have fun on Saturday — send me a photo.", exampleKo: "토요일 재밌게 보내. 사진 보내줘.", note: "거절한 뒤 상대의 일정을 축복하며 닫습니다." },
    ],
    aiRole: "이웃 Chris",
    yourRole: "정중히 거절하는 나",
    opening: "Hey! We're firing up the grill on Saturday afternoon — the whole street's coming. You in?",
    direction:
      "You are Chris, a warm and slightly persistent neighbor. Invite once more after the first refusal ('even for an hour?'). If the user holds their ground politely, accept it graciously and offer a next time. Never make them feel bad. Never correct their English.",
    round1Seconds: 150,
  },
  {
    id: "ask-for-help",
    track: "daily",
    title: "Could you give me a hand?",
    titleKo: "부탁하기",
    contextKo: "혼자 못 하는 일이 생겼습니다. 누군가에게 부탁해야 합니다.",
    goalKo: "상황 설명부터 길게 하지 말고: 부탁 먼저 → 무엇이 필요한지 → 상대 부담 줄이기.",
    modelDialogue: [
      { speaker: "you", text: "Hey, could you give me a hand with something?", ko: "저기, 뭐 하나만 도와줄 수 있어?" },
      { speaker: "ai", text: "Sure, what do you need?", ko: "그럼, 뭐가 필요해?" },
      {
        speaker: "you",
        text: "I'm moving this desk upstairs and it's heavier than I thought.",
        ko: "이 책상을 위층으로 옮기는데 생각보다 무거워서.",
      },
      { speaker: "ai", text: "Say no more. When are you doing it?", ko: "말 안 해도 돼. 언제 할 건데?" },
      {
        speaker: "you",
        text: "Whenever suits you — it'll only take ten minutes. I'd really appreciate it.",
        ko: "네가 편할 때 아무 때나. 10분이면 끝나. 정말 고마울 거야.",
      },
      { speaker: "ai", text: "How about after lunch?", ko: "점심 먹고 어때?" },
    ],
    chunks: [
      { en: "Could you give me a hand with ~?", ko: "~ 좀 도와줄 수 있어?", example: "Could you give me a hand with this desk?", exampleKo: "이 책상 옮기는 것 좀 도와줄 수 있어?", note: "Can you help me보다 가볍고 덜 부담스럽습니다." },
      { en: "It's heavier than I thought", ko: "생각보다 무거워", example: "It's heavier than I thought, honestly.", exampleKo: "솔직히 생각보다 무거워.", note: "~than I thought 은 상황 설명의 만능 틀입니다." },
      { en: "Whenever suits you", ko: "네가 편할 때 아무 때나", example: "Whenever suits you — I'm around all day.", exampleKo: "네가 편할 때 아무 때나. 나 하루 종일 있어.", note: "부탁하는 쪽이 상대에게 결정권을 넘기는 표현." },
      { en: "It'll only take ~", ko: "~면 끝나", example: "It'll only take ten minutes, I promise.", exampleKo: "10분이면 끝나, 진짜로.", note: "부담의 크기를 먼저 못 박아 상대가 수락하기 쉽게 만듭니다." },
      { en: "I'd really appreciate it", ko: "정말 고마울 거야", example: "I'd really appreciate it.", exampleKo: "정말 고마울 거야.", note: "Thank you를 미리 하는 표현. 부탁의 마침표." },
    ],
    aiRole: "같은 건물 친구 Sam",
    yourRole: "부탁하는 나",
    opening: "Hey, you looked like you were about to say something. What's up?",
    direction:
      "You are Sam, a helpful friend. Wait for the user to make the request — do not offer help before they ask. Ask what they need and when. Agree readily once they explain. If they ramble without making an actual request, ask 'so what do you need from me?'. Never correct their English.",
    round1Seconds: 150,
  },
  {
    id: "tell-what-happened",
    track: "daily",
    title: "So this happened",
    titleKo: "겪은 일 이야기하기",
    contextKo: "어제 있었던 황당한 일을 친구에게 들려줍니다.",
    goalKo: "결론부터 던지지 말고 순서대로: 배경 → 사건 → 반응. 과거형을 끝까지 유지하기.",
    modelDialogue: [
      { speaker: "ai", text: "You said something happened yesterday?", ko: "어제 무슨 일 있었다며?" },
      {
        speaker: "you",
        text: "Oh, you won't believe this. So I was on my way to work, right?",
        ko: "아, 이거 못 믿을걸. 출근하는 길이었거든?",
      },
      { speaker: "ai", text: "Okay…", ko: "응…" },
      {
        speaker: "you",
        text: "And the train just stopped. We ended up sitting there for forty minutes.",
        ko: "근데 기차가 그냥 멈춘 거야. 결국 40분을 거기 앉아 있었어.",
      },
      { speaker: "ai", text: "Forty minutes? What did you do?", ko: "40분? 그래서 뭐 했어?" },
      {
        speaker: "you",
        text: "Nothing I could do. I just gave up and called in late.",
        ko: "할 수 있는 게 없었지. 그냥 포기하고 늦는다고 전화했어.",
      },
    ],
    chunks: [
      { en: "You won't believe this", ko: "이거 못 믿을걸", example: "You won't believe what happened to me yesterday.", exampleKo: "어제 나한테 무슨 일 있었는지 못 믿을걸.", note: "이야기를 여는 장치. 상대의 귀를 열고 시작합니다." },
      { en: "So I was ~ing, right?", ko: "~하는 중이었거든?", example: "So I was on my way to work, right?", exampleKo: "출근하는 길이었거든?", note: "배경을 까는 과거진행. right? 하나로 상대를 이야기에 끌어들입니다." },
      { en: "And then ~ just ~ed", ko: "그러다 ~가 그냥 ~해버린 거야", example: "And then the train just stopped.", exampleKo: "그러다 기차가 그냥 멈춰버린 거야.", note: "just 하나가 '갑자기'의 뉘앙스를 만듭니다." },
      { en: "We ended up ~ing", ko: "결국 ~하게 됐어", example: "We ended up sitting there for forty minutes.", exampleKo: "결국 거기 40분을 앉아 있었어.", note: "의도치 않은 결과를 말하는 틀. 이야기의 허리." },
      { en: "Nothing I could do", ko: "할 수 있는 게 없었지", example: "There was nothing I could do, honestly.", exampleKo: "솔직히 할 수 있는 게 없었어.", note: "체념을 한 마디로. 짧을수록 자연스럽습니다." },
    ],
    aiRole: "이야기를 들어주는 친구 Mia",
    yourRole: "겪은 일을 들려주는 나",
    opening: "Okay, you've been holding something in all morning. What happened yesterday?",
    direction:
      "You are Mia, an engaged listener. React to each beat of the story with short interjections ('no way', 'then what?'). Ask one question that pushes the story forward. Do not tell your own story until theirs is finished. Never correct their English.",
    round1Seconds: 180,
  },
  {
    id: "food-talk",
    track: "daily",
    title: "I'll eat anything except…",
    titleKo: "음식 취향 말하기",
    contextKo: "같이 밥 먹으러 가는데 뭘 먹을지 정해야 합니다.",
    goalKo: "\"아무거나\" 금지. 먹고 싶은 것과 못 먹는 것을 분명히 말하기.",
    modelDialogue: [
      { speaker: "ai", text: "Any preference for lunch? I'm easy.", ko: "점심 뭐 먹을까? 난 아무거나 괜찮아." },
      {
        speaker: "you",
        text: "I could go for something warm. Maybe noodles?",
        ko: "따뜻한 게 당기는데. 국수 어때?",
      },
      { speaker: "ai", text: "There's a Thai place around the corner.", ko: "모퉁이에 태국 음식점 있어." },
      {
        speaker: "you",
        text: "Works for me, as long as it's not too spicy. I'm a bit of a lightweight with chili.",
        ko: "좋아, 너무 맵지만 않으면. 내가 매운 걸 좀 못 먹어서.",
      },
      { speaker: "ai", text: "They can make it mild, no problem.", ko: "순하게 해달라고 하면 돼." },
      { speaker: "you", text: "Then let's do it. I've been meaning to try that place.", ko: "그럼 가자. 거기 한번 가보고 싶었어." },
    ],
    chunks: [
      { en: "I could go for ~", ko: "~가 당기는데", example: "I could go for something warm, maybe noodles.", exampleKo: "따뜻한 게 당기는데, 국수 같은 거.", note: "I want보다 부드럽게 취향을 던지는 표현." },
      { en: "Works for me", ko: "난 좋아", example: "Thai works for me.", exampleKo: "태국 음식 좋아.", note: "수락의 가장 짧고 자연스러운 형태." },
      { en: "as long as ~", ko: "~하기만 하면", example: "Works for me, as long as it's not too spicy.", exampleKo: "좋아, 너무 맵지만 않으면.", note: "조건을 붙여 수락합니다. 무조건 yes보다 훨씬 자연스럽습니다." },
      { en: "I'm a bit of a lightweight with ~", ko: "~는 좀 못 해", example: "I'm a bit of a lightweight with chili.", exampleKo: "내가 매운 걸 좀 못 먹어.", note: "못 먹는 것을 약점이 아니라 농담처럼 말하는 표현." },
      { en: "I've been meaning to ~", ko: "~해보려고 했었어", example: "I've been meaning to try that place.", exampleKo: "거기 한번 가보려고 했었어.", note: "미뤄둔 일을 꺼낼 때. 대화에 개인적 맥락을 붙입니다." },
    ],
    aiRole: "같이 밥 먹는 동료 Ben",
    yourRole: "취향을 말해야 하는 나",
    opening: "So — lunch. I genuinely don't mind, so you pick. What are you in the mood for?",
    direction:
      "You are Ben, deliberately easygoing about food, which forces the user to decide. If they say 'anything' or 'you choose', gently bounce it back once. Suggest a place after they give any preference. Never correct their English.",
    round1Seconds: 150,
  },
  {
    id: "complain-politely",
    track: "daily",
    title: "Something's not right",
    titleKo: "정중하게 문제 제기하기",
    contextKo: "주문한 것이 잘못 나왔습니다. 화내지 않고 바로잡아야 합니다.",
    goalKo: "참고 넘어가지 말 것. 사실 → 기대했던 것 → 요청, 세 단계로 말하기.",
    modelDialogue: [
      { speaker: "you", text: "Sorry to bother you — I think there's been a mix-up.", ko: "죄송한데, 뭔가 잘못 나온 것 같아요." },
      { speaker: "ai", text: "Oh? What's the problem?", ko: "네? 어떤 문제죠?" },
      {
        speaker: "you",
        text: "I ordered the soup, but this came out instead.",
        ko: "수프를 주문했는데 이게 나왔어요.",
      },
      { speaker: "ai", text: "I'm so sorry about that. Let me check the ticket.", ko: "정말 죄송합니다. 주문서 확인해볼게요." },
      {
        speaker: "you",
        text: "No rush. Would it be possible to swap it?",
        ko: "급하진 않아요. 바꿔주실 수 있을까요?",
      },
      { speaker: "ai", text: "Of course. I'll get that sorted right away.", ko: "물론이죠. 바로 처리해드리겠습니다." },
    ],
    chunks: [
      { en: "Sorry to bother you", ko: "죄송한데요", example: "Sorry to bother you — could I ask you something?", exampleKo: "죄송한데, 뭐 좀 여쭤봐도 될까요?", note: "문제 제기의 시작. 이 쿠션이 있어야 컴플레인이 공격으로 안 들립니다." },
      { en: "I think there's been a mix-up", ko: "뭔가 잘못된 것 같아요", example: "I think there's been a mix-up with my order.", exampleKo: "제 주문이 뭔가 잘못된 것 같아요.", note: "You made a mistake를 피하고 상황 탓으로 돌리는 표현." },
      { en: "I ordered ~, but ~ came out instead", ko: "~를 주문했는데 ~가 나왔어요", example: "I ordered the soup, but this came out instead.", exampleKo: "수프를 주문했는데 이게 나왔어요.", note: "사실만 나열합니다. 감정을 빼야 빨리 해결됩니다." },
      { en: "No rush", ko: "급하진 않아요", example: "No rush, whenever you get a chance.", exampleKo: "급하진 않아요, 시간 되실 때요.", note: "요청에 여유를 붙여 상대의 방어를 낮춥니다." },
      { en: "Would it be possible to ~?", ko: "~해주실 수 있을까요?", example: "Would it be possible to swap it?", exampleKo: "바꿔주실 수 있을까요?", note: "영어에서 가장 정중한 요청 형태 중 하나." },
    ],
    aiRole: "식당 직원 Alex",
    yourRole: "문제를 말해야 하는 나",
    opening: "Here you go — one bowl of the special. Enjoy!",
    direction:
      "You are Alex, a polite server who has just delivered the wrong dish. Do not notice the mistake yourself — wait for the user to raise it. Apologize sincerely and offer to fix it once they explain. If they are vague, ask what they ordered. Never correct their English.",
    round1Seconds: 150,
  },
  {
    id: "apologize-late",
    track: "daily",
    title: "Sorry I'm late",
    titleKo: "늦었을 때 사과하기",
    contextKo: "약속에 20분 늦었습니다. 상대가 기다리고 있습니다.",
    goalKo: "변명 늘어놓지 말고: 사과 → 이유 한 줄 → 상대 배려. 세 문장 안에 끝내기.",
    modelDialogue: [
      { speaker: "you", text: "I'm so sorry — I kept you waiting.", ko: "정말 미안해. 기다리게 했네." },
      { speaker: "ai", text: "It's okay, I just got here myself.", ko: "괜찮아, 나도 방금 왔어." },
      {
        speaker: "you",
        text: "The bus never showed up. I should have left earlier.",
        ko: "버스가 안 왔어. 더 일찍 나왔어야 했는데.",
      },
      { speaker: "ai", text: "Happens to everyone. Shall we go in?", ko: "다들 그래. 들어갈까?" },
      {
        speaker: "you",
        text: "Let's do that. Dinner's on me tonight — I owe you one.",
        ko: "그러자. 오늘 저녁은 내가 살게. 신세 졌네.",
      },
      { speaker: "ai", text: "I won't say no to that.", ko: "그럼 사양 안 할게." },
    ],
    chunks: [
      { en: "I kept you waiting", ko: "기다리게 했네", example: "I'm so sorry — I kept you waiting.", exampleKo: "정말 미안해. 기다리게 했네.", note: "I'm late보다 상대 입장에서 말하는 사과. 훨씬 진심으로 들립니다." },
      { en: "~ never showed up", ko: "~가 안 왔어", example: "The bus never showed up.", exampleKo: "버스가 안 왔어.", note: "버스·사람·택배 모두에 쓰는 표현." },
      { en: "I should have ~ed", ko: "~했어야 했는데", example: "I should have left earlier.", exampleKo: "더 일찍 나왔어야 했는데.", note: "자기 책임을 한 줄 인정합니다. 이게 빠지면 변명이 됩니다." },
      { en: "It's on me", ko: "내가 살게", example: "Dinner's on me tonight.", exampleKo: "오늘 저녁은 내가 살게.", note: "말 대신 행동으로 갚는 표현." },
      { en: "I owe you one", ko: "신세 졌네", example: "Thanks for waiting — I owe you one.", exampleKo: "기다려줘서 고마워. 신세 졌네.", note: "가볍게 빚을 인정하며 관계를 닫습니다." },
    ],
    aiRole: "기다리던 친구 Dana",
    yourRole: "늦은 나",
    opening: "There you are! I was starting to think you'd forgotten.",
    direction:
      "You are Dana, a friend who has been waiting twenty minutes. Be forgiving but let a hint of having waited show in the first line. Accept the apology quickly. Move the conversation forward to the plan. Never correct their English.",
    round1Seconds: 150,
  },
  {
    id: "give-directions",
    track: "daily",
    title: "It's just around the corner",
    titleKo: "길 알려주기",
    contextKo: "길을 묻는 사람에게 방향을 설명해야 합니다.",
    goalKo: "손짓 대신 말로. 순서대로 — 방향 → 거리 → 눈에 보이는 표지 → 확인 질문.",
    modelDialogue: [
      { speaker: "ai", text: "Excuse me, do you know how to get to the station?", ko: "실례합니다, 역에 어떻게 가는지 아세요?" },
      {
        speaker: "you",
        text: "Sure — go straight down this road for about five minutes.",
        ko: "네, 이 길로 5분 정도 쭉 가세요.",
      },
      { speaker: "ai", text: "Straight down here, okay.", ko: "이쪽으로 쭉, 네." },
      {
        speaker: "you",
        text: "Then take a left at the bakery. You can't miss it — it's the big blue building.",
        ko: "그다음 빵집에서 왼쪽으로 꺾으세요. 못 지나칠 거예요, 큰 파란 건물이라.",
      },
      { speaker: "ai", text: "Left at the bakery. Got it.", ko: "빵집에서 왼쪽. 알겠습니다." },
      { speaker: "you", text: "That's it. Does that make sense?", ko: "그게 다예요. 이해되셨어요?" },
    ],
    chunks: [
      { en: "Go straight down this road", ko: "이 길로 쭉 가세요", example: "Go straight down this road for about five minutes.", exampleKo: "이 길로 5분 정도 쭉 가세요.", note: "방향 설명의 기본 뼈대. straight down 이 한 덩어리입니다." },
      { en: "for about ~ minutes", ko: "~분 정도", example: "It's about ten minutes on foot.", exampleKo: "걸어서 10분 정도예요.", note: "거리 대신 시간으로 말하는 게 훨씬 자연스럽습니다." },
      { en: "Take a left at ~", ko: "~에서 왼쪽으로 꺾으세요", example: "Take a left at the bakery.", exampleKo: "빵집에서 왼쪽으로 꺾으세요.", note: "Turn left도 되지만 take a left 가 구어에 가깝습니다." },
      { en: "You can't miss it", ko: "못 지나칠 거예요", example: "You can't miss it — it's the big blue building.", exampleKo: "못 지나칠 거예요. 큰 파란 건물이에요.", note: "상대를 안심시키는 한 마디. 설명의 마침표처럼 쓰입니다." },
      { en: "Does that make sense?", ko: "이해되셨어요?", example: "That's it. Does that make sense?", exampleKo: "그게 다예요. 이해되셨어요?", note: "설명 뒤 확인. 이게 있어야 일방적 전달이 안 됩니다." },
    ],
    aiRole: "길을 묻는 관광객 Nina",
    yourRole: "길을 알려주는 나",
    opening: "Sorry to stop you — I'm a bit lost. Do you know how to get to the station from here?",
    direction:
      "You are Nina, a lost tourist. Repeat back each step to confirm you understood. If a step is unclear, ask about that step specifically. Thank them warmly at the end. Never correct their English.",
    round1Seconds: 150,
  },
  {
    id: "elevator-30",
    track: "daily",
    title: "Thirty seconds in an elevator",
    titleKo: "엘리베이터 30초 버티기",
    contextKo: "잘 모르는 사람과 엘리베이터에 단둘이 탔습니다.",
    goalKo: "침묵을 견디지 말고 먼저 말 걸기. 날씨·건물·주말 중 하나로 시작해 두 번 주고받기.",
    modelDialogue: [
      { speaker: "you", text: "Morning. Busy one today?", ko: "안녕하세요. 오늘 바쁘세요?" },
      { speaker: "ai", text: "Always is on a Monday.", ko: "월요일은 늘 그렇죠." },
      {
        speaker: "you",
        text: "Tell me about it. At least the weather's finally turned.",
        ko: "그러니까요. 그래도 날씨는 드디어 풀렸네요.",
      },
      { speaker: "ai", text: "Right? I actually walked in today.", ko: "그렇죠? 오늘은 아예 걸어왔어요." },
      { speaker: "you", text: "Nice. That's a good way to start the day.", ko: "좋네요. 하루 시작하기 좋은 방법이죠." },
      { speaker: "ai", text: "This is me — have a good one.", ko: "저 여기서 내려요. 좋은 하루 보내세요." },
    ],
    chunks: [
      { en: "Busy one today?", ko: "오늘 바쁘세요?", example: "Morning. Busy one today?", exampleKo: "안녕하세요. 오늘 바쁘세요?", note: "완전한 문장이 아니어도 됩니다. 스몰토크는 짧을수록 자연스럽습니다." },
      { en: "Tell me about it", ko: "그러니까요", example: "Tell me about it — Mondays are the worst.", exampleKo: "그러니까요. 월요일이 제일 힘들죠.", note: "동의의 관용 표현. 직역하면 정반대로 들리니 통째로 외우세요." },
      { en: "At least ~", ko: "그래도 ~는", example: "At least the weather's finally turned.", exampleKo: "그래도 날씨는 드디어 풀렸네요.", note: "부정적 화제를 긍정으로 트는 장치. 스몰토크의 윤활유." },
      { en: "That's a good way to ~", ko: "~하기 좋은 방법이네요", example: "That's a good way to start the day.", exampleKo: "하루 시작하기 좋은 방법이네요.", note: "상대 말에 긍정적 논평을 붙여 한 턴을 더 법니다." },
      { en: "This is me", ko: "저 여기서 내려요", example: "This is me — have a good one.", exampleKo: "저 여기서 내려요. 좋은 하루 보내세요.", note: "엘리베이터·버스에서 내릴 때 쓰는 고정 표현." },
    ],
    aiRole: "같은 건물 사람 Paul",
    yourRole: "먼저 말을 거는 나",
    opening: "…",
    direction:
      "You are Paul, a neighbor in the building. Start silent — the user must break the ice. If they say nothing, make brief eye contact small talk after a while ('long week, huh?'). Keep every reply to one short sentence. Announce your floor and leave after about four exchanges. Never correct their English.",
    round1Seconds: 120,
  },
  {
    id: "talk-about-home",
    track: "daily",
    title: "Where are you based?",
    titleKo: "사는 동네 이야기하기",
    contextKo: "누가 어디 사는지 묻습니다. 동네 이야기로 이어집니다.",
    goalKo: "지명만 말하고 끝내지 말 것. 어떤 동네인지 한 문장, 좋은 점 한 문장 덧붙이기.",
    modelDialogue: [
      { speaker: "ai", text: "Whereabouts are you based?", ko: "어디 사세요?" },
      {
        speaker: "you",
        text: "I'm out west, near the river. It's quiet compared to downtown.",
        ko: "서쪽, 강 근처요. 시내보다 조용해요.",
      },
      { speaker: "ai", text: "That sounds nice. Long commute?", ko: "좋겠네요. 출퇴근은 오래 걸려요?" },
      {
        speaker: "you",
        text: "About forty minutes, but I don't mind. I get a lot of reading done.",
        ko: "40분 정도인데 괜찮아요. 책을 많이 읽게 돼서.",
      },
      { speaker: "ai", text: "That's one way to look at it.", ko: "그렇게 볼 수도 있네요." },
      { speaker: "you", text: "How about you? Are you nearby?", ko: "그쪽은요? 근처세요?" },
    ],
    chunks: [
      { en: "I'm out west, near ~", ko: "서쪽, ~ 근처요", example: "I'm out west, near the river.", exampleKo: "서쪽, 강 근처에 살아요.", note: "행정구역명 대신 방향+랜드마크. 외국인에게 훨씬 잘 전달됩니다." },
      { en: "It's quiet compared to ~", ko: "~보다 조용해요", example: "It's quiet compared to downtown.", exampleKo: "시내보다 조용해요.", note: "비교로 설명하면 그 동네를 모르는 사람도 그림이 그려집니다." },
      { en: "I don't mind", ko: "괜찮아요", example: "It's about forty minutes, but I don't mind.", exampleKo: "40분 정도인데, 저는 괜찮아요.", note: "불편을 감수한다는 뉘앙스. It's okay보다 어른스럽게 들립니다." },
      { en: "I get a lot of ~ done", ko: "~를 많이 하게 돼요", example: "I get a lot of reading done on the train.", exampleKo: "기차에서 책을 많이 읽게 돼요.", note: "시간을 어떻게 쓰는지 말하는 틀." },
      { en: "How about you? Are you nearby?", ko: "그쪽은요? 근처세요?", example: "How about you? Are you nearby?", exampleKo: "그쪽은요? 근처세요?", note: "되묻기. 스몰토크는 공을 넘겨야 이어집니다." },
    ],
    aiRole: "처음 만난 사람 Laura",
    yourRole: "내 동네를 설명하는 나",
    opening: "So, whereabouts are you based? I'm always curious how far people travel in.",
    direction:
      "You are Laura, making friendly small talk at a gathering. Ask about the commute and the neighborhood. Share one detail about your own area if they ask. Keep it light. Never correct their English.",
    round1Seconds: 150,
  },
  {
    id: "react-to-news",
    track: "daily",
    title: "Reacting to good and bad news",
    titleKo: "소식에 반응하기",
    contextKo: "상대가 좋은 소식과 나쁜 소식을 연달아 전합니다.",
    goalKo: "\"Oh, really?\"로 넘기지 말 것. 감정 → 구체적 질문 → 다음 행동 제안.",
    modelDialogue: [
      { speaker: "ai", text: "I got the job, by the way.", ko: "그나저나 나 그 일자리 붙었어." },
      { speaker: "you", text: "No way — congratulations! When do you start?", ko: "대박, 축하해! 언제 시작해?" },
      { speaker: "ai", text: "Next month. Though I'll have to move.", ko: "다음 달. 근데 이사해야 해." },
      {
        speaker: "you",
        text: "Oh, that's a big change. How are you feeling about it?",
        ko: "아, 큰 변화네. 기분이 어때?",
      },
      { speaker: "ai", text: "Honestly? A bit overwhelmed.", ko: "솔직히? 좀 벅차." },
      {
        speaker: "you",
        text: "That's completely normal. Let me know if you need a hand with the move.",
        ko: "당연한 거야. 이사할 때 손 필요하면 말해.",
      },
    ],
    chunks: [
      { en: "No way — congratulations!", ko: "대박, 축하해!", example: "No way — congratulations! That's huge.", exampleKo: "대박, 축하해! 엄청난 일이네.", note: "놀람과 축하를 한 호흡에. 리액션은 속도가 생명입니다." },
      { en: "When do you start?", ko: "언제 시작해?", example: "Congratulations! When do you start?", exampleKo: "축하해! 언제 시작해?", note: "축하 뒤에 반드시 붙는 구체적 질문. 이게 없으면 형식적으로 들립니다." },
      { en: "That's a big change", ko: "큰 변화네", example: "Oh, that's a big change.", exampleKo: "아, 큰 변화네.", note: "상대 상황의 무게를 인정하는 표현." },
      { en: "How are you feeling about it?", ko: "기분이 어때?", example: "How are you feeling about it?", exampleKo: "기분이 어때?", note: "사실이 아니라 감정을 묻습니다. 대화의 깊이가 달라집니다." },
      { en: "Let me know if you need a hand", ko: "손 필요하면 말해", example: "Let me know if you need a hand with the move.", exampleKo: "이사할 때 손 필요하면 말해.", note: "공감을 행동 제안으로 닫습니다." },
    ],
    aiRole: "친구 Tom",
    yourRole: "반응해주는 나",
    opening: "So… I've been sitting on some news all week. I got the job.",
    direction:
      "You are Tom, sharing news that is exciting but complicated. Reveal the complication only after the user reacts to the good part. Respond honestly about your feelings if asked. If the user gives a flat reaction, pause and say 'you don't sound excited' once. Never correct their English.",
    round1Seconds: 180,
  },
];
