import type { Scenario } from "./scenarios";

/**
 * 업무 트랙 확장분.
 * 회의에서 침묵하게 되는 자리를 골랐다 — 실력이 없어서가 아니라
 * 그 순간에 쓸 문장이 통째로 준비돼 있지 않아서 못 하는 말들.
 */
export const WORK_EXTRA: Scenario[] = [
  {
    id: "intro-at-meeting",
    track: "work",
    title: "Introducing yourself in a meeting",
    titleKo: "첫 미팅 자기소개",
    contextKo: "처음 들어간 프로젝트 미팅. 차례가 돌아왔습니다.",
    goalKo: "이름과 소속만 말하고 끝내지 말 것. 이름 → 역할 → 이 프로젝트에서 맡을 부분, 세 문장.",
    modelDialogue: [
      { speaker: "ai", text: "Let's go around quickly. Would you like to introduce yourself?", ko: "간단히 돌아가며 소개하죠. 소개해주시겠어요?" },
      {
        speaker: "you",
        text: "Sure. I'm Nara, I work on the data side of the marketing team.",
        ko: "네. 저는 나라이고, 마케팅팀에서 데이터 쪽을 맡고 있습니다.",
      },
      { speaker: "ai", text: "Great to have you. What will you be covering here?", ko: "반갑습니다. 여기선 어떤 걸 맡으시나요?" },
      {
        speaker: "you",
        text: "I'll be looking after the reporting side — mainly making sure the numbers line up.",
        ko: "리포팅 쪽을 맡습니다. 주로 숫자가 맞는지 확인하는 일이에요.",
      },
      { speaker: "ai", text: "Perfect, we've needed that.", ko: "좋네요, 그게 필요했습니다." },
      { speaker: "you", text: "Happy to be here. Feel free to pull me in anytime.", ko: "함께하게 돼 좋습니다. 언제든 불러주세요." },
    ],
    chunks: [
      { en: "I work on the ~ side of ~", ko: "~에서 ~ 쪽을 맡고 있습니다", example: "I work on the data side of the marketing team.", exampleKo: "마케팅팀에서 데이터 쪽을 맡고 있습니다.", note: "직함이 애매할 때 쓰는 만능 소개 틀. 한국식 직급 번역보다 잘 통합니다." },
      { en: "I'll be looking after ~", ko: "~를 맡습니다", example: "I'll be looking after the reporting side.", exampleKo: "리포팅 쪽을 맡게 됩니다.", note: "I'm in charge of보다 부드럽고 협업적으로 들립니다." },
      { en: "mainly making sure ~", ko: "주로 ~를 확인하는 일이에요", example: "Mainly making sure the numbers line up.", exampleKo: "주로 숫자가 맞는지 확인하는 일이에요.", note: "역할을 동사로 풀어줍니다. 추상적 직무명보다 훨씬 잘 전달됩니다." },
      { en: "Happy to be here", ko: "함께하게 돼 좋습니다", example: "Happy to be here — thanks for having me.", exampleKo: "함께하게 돼 좋습니다. 불러주셔서 감사합니다.", note: "소개를 따뜻하게 닫는 한 마디." },
      { en: "Feel free to pull me in anytime", ko: "언제든 불러주세요", example: "Feel free to pull me in anytime.", exampleKo: "언제든 불러주세요.", note: "협업 의사를 먼저 여는 표현. 첫인상을 바꿉니다." },
    ],
    aiRole: "프로젝트 리드 Grace",
    yourRole: "새로 합류한 나",
    opening: "Before we dive in — we've got a new face today. Would you like to introduce yourself to the group?",
    direction:
      "You are Grace, the project lead running a kickoff. Ask one follow-up about what they will cover. Welcome them warmly. Keep your turns short — this is their moment to speak. Never correct their English.",
    round1Seconds: 150,
  },
  {
    id: "explain-your-job",
    track: "work",
    title: "So what do you actually do?",
    titleKo: "내 일 설명하기",
    contextKo: "업계를 모르는 사람이 무슨 일을 하는지 묻습니다.",
    goalKo: "직함으로 답하지 말 것. 누구를 위해 → 무슨 문제를 → 어떻게 푸는지.",
    modelDialogue: [
      { speaker: "ai", text: "So what do you actually do day to day?", ko: "그래서 평소에 구체적으로 무슨 일을 하세요?" },
      {
        speaker: "you",
        text: "Basically, I help companies figure out why their training isn't sticking.",
        ko: "쉽게 말하면, 기업 교육이 왜 안 남는지를 찾아주는 일을 합니다.",
      },
      { speaker: "ai", text: "Huh. How do you even measure that?", ko: "허. 그걸 어떻게 측정해요?" },
      {
        speaker: "you",
        text: "We look at what people do three months later, not what they say on the day.",
        ko: "그날 설문이 아니라 3개월 뒤 행동을 봅니다.",
      },
      { speaker: "ai", text: "That makes sense.", ko: "말 되네요." },
      { speaker: "you", text: "It's less glamorous than it sounds, but I like it.", ko: "듣기만큼 멋있진 않은데, 저는 좋아해요." },
    ],
    chunks: [
      { en: "Basically, I help ~ figure out ~", ko: "쉽게 말하면, ~가 ~를 알아내도록 돕습니다", example: "Basically, I help companies figure out why their training isn't sticking.", exampleKo: "쉽게 말하면, 기업 교육이 왜 안 남는지를 찾아주는 일을 합니다.", note: "직함 대신 '누구를 돕는가'로 시작하는 틀. 어떤 직업에도 들어맞습니다." },
      { en: "day to day", ko: "평소에, 일상적으로", example: "Day to day, I'm mostly talking to people and reading data.", exampleKo: "평소엔 주로 사람들 만나고 데이터 보는 일을 합니다.", note: "구체적인 업무를 물을 때 붙는 관용 표현." },
      { en: "We look at ~, not ~", ko: "~가 아니라 ~를 봅니다", example: "We look at what people do three months later, not what they say on the day.", exampleKo: "그날 설문이 아니라 3개월 뒤 행동을 봅니다.", note: "대비 구조. 내 일의 차별점을 한 문장으로 만듭니다." },
      { en: "It's less ~ than it sounds", ko: "듣기만큼 ~하진 않아요", example: "It's less glamorous than it sounds.", exampleKo: "듣기만큼 멋있진 않아요.", note: "겸손과 유머를 동시에. 대화를 편하게 만듭니다." },
      { en: "but I like it", ko: "근데 저는 좋아해요", example: "It's a lot of spreadsheets, but I like it.", exampleKo: "스프레드시트 투성이인데, 저는 좋아해요.", note: "설명을 감정으로 닫습니다. 이게 없으면 보고가 됩니다." },
    ],
    aiRole: "업계 밖 지인 Oliver",
    yourRole: "내 일을 설명하는 나",
    opening: "I've told people you work in training, but honestly I have no idea what that means. What do you actually do?",
    direction:
      "You are Oliver, an outsider with zero industry knowledge and genuine curiosity. If the user uses jargon, say you did not follow and ask them to put it simply. Ask one 'how' question. Never correct their English.",
    round1Seconds: 180,
  },
  {
    id: "ask-clarification",
    track: "work",
    title: "Sorry, could you run that by me again?",
    titleKo: "못 알아들었을 때 되묻기",
    contextKo: "상대가 빠르게 설명했는데 절반을 놓쳤습니다.",
    goalKo: "알아들은 척 금지. 어디까지 이해했는지 말하고, 정확히 무엇이 막히는지 짚어 되묻기.",
    modelDialogue: [
      {
        speaker: "ai",
        text: "So we'll deprecate the old endpoint, migrate the clients in batches, and flip the flag on Friday.",
        ko: "기존 엔드포인트를 폐기하고, 클라이언트를 배치로 이전한 뒤, 금요일에 플래그를 전환합니다.",
      },
      { speaker: "you", text: "Sorry, could you run that by me again?", ko: "죄송한데, 다시 한 번 말씀해주시겠어요?" },
      { speaker: "ai", text: "Sure — which part?", ko: "네, 어느 부분이요?" },
      {
        speaker: "you",
        text: "I followed the first bit. I lost you at the batches — what does that mean for us?",
        ko: "앞부분은 따라갔어요. 배치 얘기에서 놓쳤는데, 그게 저희한테 무슨 뜻이죠?",
      },
      { speaker: "ai", text: "Ah — it means you'd move about twenty clients a day.", ko: "아, 하루에 클라이언트 20개 정도씩 옮긴다는 뜻입니다." },
      { speaker: "you", text: "Got it. So just to be clear, nothing changes before Friday?", ko: "알겠습니다. 그럼 확실히 하자면, 금요일 전까진 바뀌는 게 없는 거죠?" },
    ],
    chunks: [
      { en: "Could you run that by me again?", ko: "다시 한 번 말씀해주시겠어요?", example: "Sorry, could you run that by me again?", exampleKo: "죄송한데, 다시 한 번 말씀해주시겠어요?", note: "Pardon? 보다 어른스럽고, 되묻는 걸 무능해 보이지 않게 합니다." },
      { en: "I followed the first bit", ko: "앞부분은 따라갔어요", example: "I followed the first bit, but not the rest.", exampleKo: "앞부분은 따라갔는데, 뒤는 못 따라갔어요.", note: "이해한 만큼을 먼저 밝힙니다. 통째로 못 알아들은 게 아님을 보여줍니다." },
      { en: "I lost you at ~", ko: "~에서 놓쳤어요", example: "I lost you at the batches — what does that mean?", exampleKo: "배치 얘기에서 놓쳤어요. 그게 무슨 뜻이죠?", note: "막힌 지점을 정확히 지목하는 표현. 상대의 설명 시간을 아껴줍니다." },
      { en: "What does that mean for us?", ko: "그게 저희한테 무슨 뜻이죠?", example: "What does that mean for us, practically?", exampleKo: "실무적으로 저희한테 무슨 뜻이죠?", note: "정보를 내 상황으로 번역해달라는 요청." },
      { en: "Just to be clear, ~?", ko: "확실히 하자면, ~죠?", example: "Just to be clear, nothing changes before Friday?", exampleKo: "확실히 하자면, 금요일 전까진 바뀌는 게 없는 거죠?", note: "이해한 내용을 되짚어 확인합니다. 회의에서 가장 유용한 한 문장." },
    ],
    aiRole: "말이 빠른 동료 엔지니어 Raj",
    yourRole: "확인해야 하는 나",
    opening:
      "Right, quick sync — we'll deprecate the old endpoint, migrate the clients in batches, and flip the flag on Friday. You good with that?",
    direction:
      "You are Raj, a fast-talking engineer who uses jargon without noticing. Answer clarification questions helpfully and more slowly. If the user just says 'okay' without checking anything, add one more dense sentence. Never correct their English.",
    round1Seconds: 180,
  },
  {
    id: "share-progress",
    track: "work",
    title: "Where are we with that?",
    titleKo: "진행 상황 공유하기",
    contextKo: "상사가 맡긴 일의 진행 상황을 묻습니다.",
    goalKo: "\"아직 하고 있어요\" 금지. 끝난 것 → 남은 것 → 언제 끝나는지, 숫자로.",
    modelDialogue: [
      { speaker: "ai", text: "Where are we with the survey?", ko: "설문은 어디까지 됐죠?" },
      {
        speaker: "you",
        text: "We're about two thirds through. The questions are locked and it's out to three teams.",
        ko: "3분의 2 정도 왔습니다. 문항은 확정됐고 세 팀에 발송됐어요.",
      },
      { speaker: "ai", text: "And the rest?", ko: "나머지는요?" },
      {
        speaker: "you",
        text: "Two teams left. I should have everything in by Wednesday.",
        ko: "두 팀 남았습니다. 수요일까지는 다 들어올 것 같습니다.",
      },
      { speaker: "ai", text: "Anything blocking you?", ko: "막히는 건 없고요?" },
      {
        speaker: "you",
        text: "Nothing on my side. I'll flag it straight away if that changes.",
        ko: "제 쪽엔 없습니다. 생기면 바로 알려드릴게요.",
      },
    ],
    chunks: [
      { en: "We're about ~ through", ko: "~ 정도 왔습니다", example: "We're about two thirds through.", exampleKo: "3분의 2 정도 왔습니다.", note: "진행률을 분수나 퍼센트로. '거의 다 됐어요'는 아무 정보가 없습니다." },
      { en: "~ is locked", ko: "~는 확정됐습니다", example: "The questions are locked.", exampleKo: "문항은 확정됐습니다.", note: "끝난 것을 확정형으로 말합니다. 진행 중과 완료를 구분해야 신뢰가 쌓입니다." },
      { en: "I should have ~ by ~", ko: "~까지는 ~될 것 같습니다", example: "I should have everything in by Wednesday.", exampleKo: "수요일까지는 다 들어올 것 같습니다.", note: "날짜를 넣되 단정은 피하는 표현." },
      { en: "Anything blocking you?", ko: "막히는 건 없어요?", example: "Anything blocking you on that?", exampleKo: "그거 진행에 막히는 건 없고요?", note: "상사가 던지는 질문. 알아듣고 바로 답할 수 있어야 합니다." },
      { en: "I'll flag it straight away", ko: "생기면 바로 알려드리겠습니다", example: "I'll flag it straight away if that changes.", exampleKo: "상황이 바뀌면 바로 알려드리겠습니다.", note: "리스크 관리 의사를 보여주는 마무리." },
    ],
    aiRole: "직속 상사 Rachel",
    yourRole: "보고하는 나",
    opening: "Got two minutes? I just want a quick read on where we are with the survey.",
    direction:
      "You are Rachel, a manager who wants specifics, not reassurance. If the user is vague ('almost done', 'working on it'), ask for a number or a date. Ask if anything is blocking them. Keep it brisk and friendly. Never correct their English.",
    round1Seconds: 150,
  },
  {
    id: "give-feedback",
    track: "work",
    title: "Can I give you some feedback?",
    titleKo: "동료에게 피드백 주기",
    contextKo: "동료의 결과물에 문제가 있습니다. 말해야 하는데 관계도 지켜야 합니다.",
    goalKo: "돌려 말하다 흐지부지 금지. 관찰 → 영향 → 제안, 세 단계로 명확하게.",
    modelDialogue: [
      { speaker: "you", text: "Have you got a minute? I wanted to share some thoughts on the deck.", ko: "잠깐 시간 돼요? 자료에 대해 의견 좀 드리고 싶어서요." },
      { speaker: "ai", text: "Of course, go ahead.", ko: "네, 말씀하세요." },
      {
        speaker: "you",
        text: "The analysis is solid. What I noticed is that the ask doesn't come until slide nine.",
        ko: "분석은 탄탄해요. 다만 요청 사항이 9페이지에 가서야 나오더라고요.",
      },
      { speaker: "ai", text: "Hmm, I hadn't thought about that.", ko: "음, 그건 생각 못 했네요." },
      {
        speaker: "you",
        text: "It means they might tune out before they get there. Could we move it to the front?",
        ko: "그러면 거기 닿기 전에 관심이 꺼질 수 있어요. 앞으로 옮기면 어떨까요?",
      },
      { speaker: "ai", text: "Yeah, that's fair. Let me restructure it.", ko: "네, 일리 있네요. 구조를 다시 잡을게요." },
    ],
    chunks: [
      { en: "I wanted to share some thoughts on ~", ko: "~에 대해 의견 좀 드리고 싶어서요", example: "I wanted to share some thoughts on the deck.", exampleKo: "자료에 대해 의견 좀 드리고 싶어서요.", note: "feedback 이라는 단어를 피해 방어를 낮추는 시작." },
      { en: "What I noticed is that ~", ko: "제가 본 건 ~라는 점이에요", example: "What I noticed is that the ask doesn't come until slide nine.", exampleKo: "제가 본 건 요청 사항이 9페이지에 가서야 나온다는 점이에요.", note: "You didn't ~ 대신 관찰로 말합니다. 비난이 아니라 사실이 됩니다." },
      { en: "It means they might ~", ko: "그러면 ~할 수 있어요", example: "It means they might tune out before they get there.", exampleKo: "그러면 거기 닿기 전에 관심이 꺼질 수 있어요.", note: "문제의 결과를 짚습니다. 이게 있어야 취향이 아니라 근거가 됩니다." },
      { en: "Could we ~?", ko: "~하면 어떨까요?", example: "Could we move it to the front?", exampleKo: "그걸 앞으로 옮기면 어떨까요?", note: "You should 대신 we. 같은 편이라는 신호." },
      { en: "That's fair", ko: "일리 있네요", example: "Yeah, that's fair.", exampleKo: "네, 일리 있네요.", note: "피드백을 받았을 때 쓰는 표현. 반대로도 알아둬야 합니다." },
    ],
    aiRole: "동료 Priya",
    yourRole: "피드백을 주는 나",
    opening: "You wanted to talk about the deck? I'm pretty happy with how it turned out.",
    direction:
      "You are Priya, a competent colleague who is slightly attached to her work. Be receptive but ask 'what would you do instead?' if the user only criticizes without suggesting. Accept a well-reasoned point. Never correct their English.",
    round1Seconds: 180,
  },
  {
    id: "say-no-to-extra",
    track: "work",
    title: "I can't take that on right now",
    titleKo: "추가 업무 거절하기",
    contextKo: "이미 일이 꽉 찼는데 하나 더 들어옵니다.",
    goalKo: "그냥 받지 말 것. 현재 부하 설명 → 거절 → 대안(우선순위 조정이나 다른 시점) 제시.",
    modelDialogue: [
      { speaker: "ai", text: "Could you take the onboarding deck as well? It's not a big one.", ko: "온보딩 자료도 맡아줄 수 있어요? 크진 않아요." },
      {
        speaker: "you",
        text: "I'd like to help, but I'm at capacity this week.",
        ko: "돕고 싶은데, 이번 주는 여력이 없습니다.",
      },
      { speaker: "ai", text: "Ah. It is fairly urgent though.", ko: "아. 근데 좀 급하긴 한데요." },
      {
        speaker: "you",
        text: "I understand. If it takes priority over the report, I can shift things around.",
        ko: "이해합니다. 보고서보다 우선이라면 일정을 조정할 수 있습니다.",
      },
      { speaker: "ai", text: "No, the report comes first.", ko: "아니요, 보고서가 먼저예요." },
      {
        speaker: "you",
        text: "Then I could pick it up on Monday. Would that still work?",
        ko: "그럼 월요일에 착수할 수 있습니다. 그래도 괜찮을까요?",
      },
    ],
    chunks: [
      { en: "I'd like to help, but ~", ko: "돕고 싶은데, ~", example: "I'd like to help, but I'm at capacity this week.", exampleKo: "돕고 싶은데, 이번 주는 여력이 없습니다.", note: "거절 앞의 쿠션. 의지는 있다는 신호를 먼저 줍니다." },
      { en: "I'm at capacity", ko: "여력이 없습니다", example: "I'm at capacity until Friday.", exampleKo: "금요일까지는 여력이 없습니다.", note: "I'm busy보다 전문적으로 들립니다. 감정이 아니라 용량의 문제로 프레이밍합니다." },
      { en: "If it takes priority over ~", ko: "~보다 우선이라면", example: "If it takes priority over the report, I can shift things around.", exampleKo: "보고서보다 우선이라면 일정을 조정할 수 있습니다.", note: "거절을 우선순위 질문으로 바꿉니다. 결정 책임을 상대에게 돌려주는 기술." },
      { en: "I can shift things around", ko: "일정을 조정할 수 있습니다", example: "I can shift things around if you need it sooner.", exampleKo: "더 빨리 필요하시면 일정을 조정할 수 있습니다.", note: "유연함을 보이되 공짜는 아니라는 뜻." },
      { en: "Would that still work?", ko: "그래도 괜찮을까요?", example: "I could pick it up on Monday — would that still work?", exampleKo: "월요일에 착수할 수 있는데, 그래도 괜찮을까요?", note: "대안을 던지고 확인으로 닫습니다." },
    ],
    aiRole: "다른 팀 매니저 Kevin",
    yourRole: "거절해야 하는 나",
    opening: "Hey, quick favour — could you take on the onboarding deck this week? Shouldn't be much work.",
    direction:
      "You are Kevin, a manager from another team who wants a yes. Push once with urgency. When the user asks you to choose a priority, make a clear choice. Accept a reasonable alternative timeline. Never correct their English.",
    round1Seconds: 180,
  },
  {
    id: "negotiate-scope",
    track: "work",
    title: "That's doable, but not all of it",
    titleKo: "업무 범위 조정하기",
    contextKo: "요청받은 일이 주어진 시간에 다 들어가지 않습니다.",
    goalKo: "전부 못 한다고만 하지 말 것. 무엇이 되는지 먼저 말하고, 무엇을 빼야 하는지 제안하기.",
    modelDialogue: [
      { speaker: "ai", text: "So we'd need all three regions analysed by Friday.", ko: "그럼 금요일까지 세 지역 분석이 다 필요해요." },
      {
        speaker: "you",
        text: "One region by Friday is realistic. All three isn't, not properly.",
        ko: "금요일까지 한 지역은 가능합니다. 세 곳 전부는 제대로는 어렵습니다.",
      },
      { speaker: "ai", text: "Hmm. What would you suggest?", ko: "음. 어떻게 하면 좋을까요?" },
      {
        speaker: "you",
        text: "We could start with the biggest market and follow up with the other two next week.",
        ko: "가장 큰 시장부터 하고, 나머지 둘은 다음 주에 이어가면 됩니다.",
      },
      { speaker: "ai", text: "That could work. Would the first one be complete?", ko: "그거 괜찮겠네요. 첫 번째는 완성본인가요?" },
      { speaker: "you", text: "Yes — I'd rather do one well than three halfway.", ko: "네. 셋을 반쯤 하느니 하나를 제대로 하는 게 낫습니다." },
    ],
    chunks: [
      { en: "~ by Friday is realistic", ko: "금요일까지 ~는 가능합니다", example: "One region by Friday is realistic.", exampleKo: "금요일까지 한 지역은 가능합니다.", note: "되는 것부터 말합니다. 거절로 시작하면 협상이 닫힙니다." },
      { en: "not properly", ko: "제대로는 아니고요", example: "All three isn't — not properly.", exampleKo: "세 곳 전부는 제대로는 어렵습니다.", note: "가능/불가능이 아니라 품질의 문제로 재정의하는 두 단어." },
      { en: "We could start with ~ and follow up with ~", ko: "~부터 하고 ~는 이어서", example: "We could start with the biggest market and follow up with the other two next week.", exampleKo: "가장 큰 시장부터 하고, 나머지 둘은 다음 주에 이어가면 됩니다.", note: "쪼개서 제안하는 틀. 범위 협상의 핵심 문장." },
      { en: "What would you suggest?", ko: "어떻게 하면 좋을까요?", example: "What would you suggest we do instead?", exampleKo: "그럼 어떻게 하는 게 좋을까요?", note: "상대가 이걸 물으면 준비된 대안을 바로 내야 합니다." },
      { en: "I'd rather ~ than ~", ko: "~하느니 ~하는 게 낫습니다", example: "I'd rather do one well than three halfway.", exampleKo: "셋을 반쯤 하느니 하나를 제대로 하는 게 낫습니다.", note: "기준을 드러내는 표현. 전문가로 보이게 만드는 문장." },
    ],
    aiRole: "클라이언트 담당 Sophie",
    yourRole: "범위를 조정하는 나",
    opening: "Before we commit — we'd need all three regions analysed by Friday. Can you make that happen?",
    direction:
      "You are Sophie, a client-facing colleague under pressure. Ask 'what would you suggest?' once the user pushes back. Accept a concrete phased plan. If they simply say no with no alternative, ask what they can do instead. Never correct their English.",
    round1Seconds: 180,
  },
  {
    id: "present-numbers",
    track: "work",
    title: "Walking through the numbers",
    titleKo: "숫자로 설명하기",
    contextKo: "실적 숫자를 두고 짧게 설명해야 합니다.",
    goalKo: "숫자만 읽지 말 것. 숫자 → 비교 대상 → 이유 → 그래서 무엇을 할지.",
    modelDialogue: [
      { speaker: "ai", text: "Can you walk us through the numbers?", ko: "숫자 좀 설명해주시겠어요?" },
      {
        speaker: "you",
        text: "Sure. We're at sixty-two percent, which is up from fifty-five last quarter.",
        ko: "네. 62%인데, 지난 분기 55%에서 올랐습니다.",
      },
      { speaker: "ai", text: "What's driving that?", ko: "뭐 때문이죠?" },
      {
        speaker: "you",
        text: "Mostly the new onboarding flow. It accounts for roughly two thirds of the increase.",
        ko: "대부분 새 온보딩 흐름입니다. 증가분의 3분의 2 정도를 차지합니다.",
      },
      { speaker: "ai", text: "And the rest?", ko: "나머지는요?" },
      {
        speaker: "you",
        text: "Seasonal, most likely. So my read is we hold the course and check again in a month.",
        ko: "계절 요인일 가능성이 큽니다. 그래서 제 판단은, 유지하고 한 달 뒤 다시 보는 겁니다.",
      },
    ],
    chunks: [
      { en: "We're at ~, which is up from ~", ko: "~인데, ~에서 올랐습니다", example: "We're at sixty-two percent, which is up from fifty-five last quarter.", exampleKo: "62%인데, 지난 분기 55%에서 올랐습니다.", note: "숫자에 반드시 비교 대상을 붙입니다. 단독 숫자는 의미가 없습니다." },
      { en: "What's driving that?", ko: "뭐 때문이죠?", example: "What's driving that increase?", exampleKo: "그 증가는 뭐 때문이죠?", note: "숫자 발표 뒤 100% 나오는 질문. 답을 미리 준비해두세요." },
      { en: "It accounts for roughly ~", ko: "~ 정도를 차지합니다", example: "It accounts for roughly two thirds of the increase.", exampleKo: "증가분의 3분의 2 정도를 차지합니다.", note: "기여도를 말하는 표현. roughly 가 과신을 피하게 해줍니다." },
      { en: "most likely", ko: "가능성이 큽니다", example: "Seasonal, most likely.", exampleKo: "계절 요인일 가능성이 큽니다.", note: "확신의 정도를 조절하는 부사. 모르는 걸 아는 척하지 않아도 됩니다." },
      { en: "My read is ~", ko: "제 판단은 ~입니다", example: "My read is we hold the course and check again in a month.", exampleKo: "제 판단은 유지하고 한 달 뒤 다시 보자는 겁니다.", note: "숫자를 해석으로 닫습니다. 이게 있어야 보고가 아니라 의견이 됩니다." },
    ],
    aiRole: "팀장 Marcus",
    yourRole: "숫자를 설명하는 나",
    opening: "Okay, the floor's yours — can you walk us through where the numbers landed this quarter?",
    direction:
      "You are Marcus, a team lead who always asks why. After any number, ask what is driving it. Ask one follow-up about the remainder. If the user only recites figures without interpretation, ask 'so what do we do with that?'. Never correct their English.",
    round1Seconds: 180,
  },
  {
    id: "client-kickoff",
    track: "work",
    title: "First call with a client",
    titleKo: "클라이언트 첫 통화",
    contextKo: "새 클라이언트와의 첫 화상 미팅. 첫 3분을 이끌어야 합니다.",
    goalKo: "바로 본론 금지. 가벼운 인사 → 오늘 다룰 것 → 상대가 원하는 것 확인.",
    modelDialogue: [
      { speaker: "you", text: "Thanks for making the time. Can you hear me okay?", ko: "시간 내주셔서 감사합니다. 소리 잘 들리시나요?" },
      { speaker: "ai", text: "Loud and clear.", ko: "잘 들립니다." },
      {
        speaker: "you",
        text: "Great. I thought we'd cover three things today — scope, timeline, and who does what.",
        ko: "좋습니다. 오늘은 세 가지를 다루려고 합니다. 범위, 일정, 역할 분담이요.",
      },
      { speaker: "ai", text: "Sounds good.", ko: "좋습니다." },
      {
        speaker: "you",
        text: "Before I start — is there anything you'd like to add to that list?",
        ko: "시작하기 전에, 더 다루고 싶으신 건 없으실까요?",
      },
      { speaker: "ai", text: "Actually, yes — I'd like to talk about budget.", ko: "아, 있습니다. 예산 얘기를 하고 싶어요." },
    ],
    chunks: [
      { en: "Thanks for making the time", ko: "시간 내주셔서 감사합니다", example: "Thanks for making the time today.", exampleKo: "오늘 시간 내주셔서 감사합니다.", note: "미팅을 여는 가장 안전한 한 문장." },
      { en: "Can you hear me okay?", ko: "소리 잘 들리시나요?", example: "Can you hear me okay?", exampleKo: "소리 잘 들리시나요?", note: "화상 미팅의 필수 확인. 이 한 마디로 어색한 첫 5초를 넘깁니다." },
      { en: "I thought we'd cover ~", ko: "오늘은 ~를 다루려고 합니다", example: "I thought we'd cover three things today.", exampleKo: "오늘은 세 가지를 다루려고 합니다.", note: "의제를 부드럽게 제시하는 틀. We will보다 덜 일방적입니다." },
      { en: "Before I start — ", ko: "시작하기 전에", example: "Before I start — is there anything you'd like to add?", exampleKo: "시작하기 전에, 더 하실 말씀 있으실까요?", note: "상대에게 발언권을 먼저 넘기는 장치." },
      { en: "anything you'd like to add?", ko: "더 다루고 싶으신 건 없으실까요?", example: "Is there anything you'd like to add to that list?", exampleKo: "그 목록에 더하고 싶으신 건 없으실까요?", note: "의제를 함께 만듭니다. 클라이언트가 주도권을 느끼게 합니다." },
    ],
    aiRole: "클라이언트 담당자 Mr. Weber",
    yourRole: "미팅을 여는 나",
    opening: "Hi — sorry, I think I just joined. Are we all here?",
    direction:
      "You are Mr. Weber, a polite but busy client on a first call. Answer briefly. When asked if you want to add anything, raise budget. Expect the user to lead the call. If they go silent, ask 'so how would you like to run this?'. Never correct their English.",
    round1Seconds: 180,
  },
  {
    id: "handover",
    track: "work",
    title: "Handing over your work",
    titleKo: "인수인계 설명하기",
    contextKo: "휴가를 앞두고 동료에게 업무를 넘겨야 합니다.",
    goalKo: "다 설명하려 하지 말 것. 매일 할 것 → 터질 수 있는 것 → 그때 누구에게.",
    modelDialogue: [
      { speaker: "you", text: "Let me walk you through what needs watching while I'm out.", ko: "제가 없는 동안 봐주셔야 할 것들을 짚어드릴게요." },
      { speaker: "ai", text: "Go ahead, I'm taking notes.", ko: "네, 적고 있어요." },
      {
        speaker: "you",
        text: "The daily report goes out at nine. It's automated, so you just need to check it landed.",
        ko: "일일 보고는 9시에 나갑니다. 자동이라 발송됐는지만 확인하면 돼요.",
      },
      { speaker: "ai", text: "And if it doesn't?", ko: "안 나가면요?" },
      {
        speaker: "you",
        text: "Then ping Dan — he's the one who can rerun it. That's the only thing likely to break.",
        ko: "그럼 Dan한테 연락하세요. 재실행할 수 있는 사람이에요. 터질 만한 건 그거 하나뿐입니다.",
      },
      { speaker: "ai", text: "Got it. Anything else?", ko: "알겠습니다. 다른 건요?" },
    ],
    chunks: [
      { en: "Let me walk you through ~", ko: "~를 짚어드릴게요", example: "Let me walk you through what needs watching.", exampleKo: "봐주셔야 할 것들을 짚어드릴게요.", note: "설명을 여는 표현. 상대에게 따라올 준비를 시킵니다." },
      { en: "what needs watching", ko: "봐주셔야 할 것", example: "Here's what needs watching while I'm out.", exampleKo: "제가 없는 동안 봐주셔야 할 건 이겁니다.", note: "할 일 목록이 아니라 '지켜볼 것'으로 프레이밍하면 인수인계가 짧아집니다." },
      { en: "you just need to ~", ko: "~만 하시면 돼요", example: "You just need to check it landed.", exampleKo: "발송됐는지만 확인하시면 돼요.", note: "상대의 부담을 줄이는 말. 인수인계의 핵심은 범위를 좁히는 것." },
      { en: "Then ping ~", ko: "그럼 ~한테 연락하세요", example: "Then ping Dan — he can rerun it.", exampleKo: "그럼 Dan한테 연락하세요. 재실행할 수 있어요.", note: "에스컬레이션 경로를 사람 이름으로. 부서명보다 훨씬 실용적입니다." },
      { en: "That's the only thing likely to break", ko: "터질 만한 건 그거 하나입니다", example: "That's the only thing likely to break.", exampleKo: "터질 만한 건 그거 하나입니다.", note: "리스크를 한정해줍니다. 받는 사람이 가장 듣고 싶어 하는 문장." },
    ],
    aiRole: "업무를 넘겨받는 동료 Yuki",
    yourRole: "인수인계하는 나",
    opening: "Okay, I'm all yours. What do I need to know for the two weeks you're away?",
    direction:
      "You are Yuki, taking over the user's work. Ask practical what-if questions ('and if it doesn't?', 'who do I ask?'). Confirm each item back briefly. Never correct their English.",
    round1Seconds: 180,
  },
  {
    id: "interview-answer",
    track: "work",
    title: "Tell me about yourself",
    titleKo: "면접: 강점과 약점",
    contextKo: "영어 면접. 가장 흔한 두 질문이 나옵니다.",
    goalKo: "형용사 나열 금지. 주장 → 근거가 되는 사례 한 줄 → 결과.",
    modelDialogue: [
      { speaker: "ai", text: "What would you say your biggest strength is?", ko: "본인의 가장 큰 강점은 뭐라고 생각하세요?" },
      {
        speaker: "you",
        text: "I'd say it's turning messy problems into something people can act on.",
        ko: "정리 안 된 문제를 실행 가능한 형태로 만드는 것이라고 봅니다.",
      },
      { speaker: "ai", text: "Can you give me an example?", ko: "예를 들어주실 수 있나요?" },
      {
        speaker: "you",
        text: "Last year our training feedback was all over the place, so I rebuilt it around three questions. Response rates doubled.",
        ko: "작년에 교육 피드백이 엉망이어서 세 개 질문으로 다시 설계했습니다. 응답률이 두 배가 됐어요.",
      },
      { speaker: "ai", text: "And a weakness?", ko: "약점은요?" },
      {
        speaker: "you",
        text: "I tend to over-prepare. I've been working on setting a time limit and shipping it.",
        ko: "준비를 과하게 하는 편입니다. 시간을 정해놓고 내보내는 연습을 하고 있습니다.",
      },
    ],
    chunks: [
      { en: "I'd say it's ~", ko: "~라고 봅니다", example: "I'd say it's turning messy problems into something people can act on.", exampleKo: "정리 안 된 문제를 실행 가능한 형태로 만드는 것이라고 봅니다.", note: "단정 대신 견해로. 강점을 말할 때 덜 뻔뻔하게 들립니다." },
      { en: "Can you give me an example?", ko: "예를 들어주실 수 있나요?", example: "Can you give me an example of that?", exampleKo: "그거 예를 들어주실 수 있나요?", note: "면접에서 반드시 따라오는 질문. 사례를 미리 준비해야 합니다." },
      { en: "~ was all over the place, so I ~", ko: "~가 엉망이어서 제가 ~했습니다", example: "Our feedback was all over the place, so I rebuilt it around three questions.", exampleKo: "피드백이 엉망이어서 세 개 질문으로 다시 설계했습니다.", note: "문제와 행동을 한 문장에 묶는 사례 서술의 뼈대." },
      { en: "I tend to ~", ko: "~하는 편입니다", example: "I tend to over-prepare.", exampleKo: "준비를 과하게 하는 편입니다.", note: "약점을 성격이 아니라 경향으로 말합니다. 고칠 수 있는 것처럼 들립니다." },
      { en: "I've been working on ~", ko: "~하는 연습을 하고 있습니다", example: "I've been working on setting a time limit and shipping it.", exampleKo: "시간을 정해놓고 내보내는 연습을 하고 있습니다.", note: "약점 답변의 필수 후반부. 이게 없으면 자기 고백으로 끝납니다." },
    ],
    aiRole: "면접관 Ms. Patel",
    yourRole: "지원자 나",
    opening: "Thanks for coming in. Let's start simple — what would you say your biggest strength is?",
    direction:
      "You are Ms. Patel, a calm interviewer. Always ask for a concrete example after any claim. Ask about a weakness in the second half. Do not give encouragement or evaluation during the interview. Never correct their English.",
    round1Seconds: 180,
  },
  {
    id: "conference-network",
    track: "work",
    title: "Working the room",
    titleKo: "컨퍼런스에서 말 걸기",
    contextKo: "행사 쉬는 시간. 혼자 서 있는 사람에게 다가갑니다.",
    goalKo: "명함부터 내밀지 말 것. 공통 화제로 시작 → 서로 소개 → 다음 연결 제안.",
    modelDialogue: [
      { speaker: "you", text: "Did you catch the morning session?", ko: "오전 세션 보셨어요?" },
      { speaker: "ai", text: "I did. Bit longer than it needed to be.", ko: "봤어요. 좀 길었죠." },
      {
        speaker: "you",
        text: "Right? Though the part about retention was worth it. I'm Nara, by the way.",
        ko: "그렇죠? 근데 리텐션 얘기는 들을 만했어요. 아, 저는 나라예요.",
      },
      { speaker: "ai", text: "Good to meet you. I'm Tobias — I work in product.", ko: "반갑습니다. 저는 토비아스고, 프로덕트 쪽입니다." },
      {
        speaker: "you",
        text: "Oh, then you'd have opinions about that last slide. What did you make of it?",
        ko: "오, 그럼 마지막 슬라이드에 할 말 있으시겠네요. 어떻게 보셨어요?",
      },
      { speaker: "ai", text: "Honestly, I wasn't convinced.", ko: "솔직히 설득되진 않았어요." },
    ],
    chunks: [
      { en: "Did you catch ~?", ko: "~ 보셨어요?", example: "Did you catch the morning session?", exampleKo: "오전 세션 보셨어요?", note: "낯선 사람에게 말 거는 가장 안전한 시작. 공통 경험부터 짚습니다." },
      { en: "Bit longer than it needed to be", ko: "좀 길었죠", example: "Bit longer than it needed to be, honestly.", exampleKo: "솔직히 좀 길었죠.", note: "가벼운 불평은 낯선 사이를 빠르게 좁힙니다." },
      { en: "I'm ~, by the way", ko: "아, 저는 ~예요", example: "I'm Nara, by the way.", exampleKo: "아, 저는 나라예요.", note: "대화가 시작된 뒤에 이름을 끼워 넣습니다. 처음부터 하면 영업처럼 들립니다." },
      { en: "then you'd have opinions about ~", ko: "그럼 ~에 할 말 있으시겠네요", example: "Oh, then you'd have opinions about that last slide.", exampleKo: "오, 그럼 마지막 슬라이드에 할 말 있으시겠네요.", note: "상대의 직업을 대화 소재로 되돌려주는 기술." },
      { en: "What did you make of it?", ko: "어떻게 보셨어요?", example: "What did you make of it?", exampleKo: "그거 어떻게 보셨어요?", note: "What did you think보다 세련되고, 의견을 끌어내기 좋습니다." },
    ],
    aiRole: "행사 참가자 Tobias",
    yourRole: "말을 거는 나",
    opening: "…",
    direction:
      "You are Tobias, standing alone with a coffee at a conference break. Do not speak first — the user approaches you. Be a little reserved at first, then warm up once they show genuine interest. Offer your name and field after they offer theirs. Never correct their English.",
    round1Seconds: 180,
  },
];
